### ISSUE TITLE
Replace bespoke DID dereference implementation with web5/dids after update

### ISSUE THREAD

**Issue by diehuxx** [TBD54566975/tbdex-js#147]
Context: https://github.com/TBD54566975/tbdex-js/pull/141#discussion_r1454398823

**Comment by jiyoontbd** [comment]
i see that did-resolver in `@web5/dids` have `resolve()` as well, but in tbdex we are currently using `resolveDids()` in our own did-resolvers.ts. 

should we try to replace tbdex's `resolveDid()` with web5's `resolve()` in this ticket?
