### ISSUE TITLE
Split `TbdexHttpClient.sendMessage()` into separate methods `createExchange()`, `submitOrder()`, and `submitClose()`

### ISSUE THREAD

**Issue by diehuxx** [TBD54566975/tbdex-js#187]
`sendMessage` is misleading for two reasons.
1. The client should not be able to send just any message to a PFI. They should only be able to send RFQs, Orders, and Closes. Other message kinds are created and sent by the PFI.
2. `sendMessage` sends to several different endpoints with different options. We are using clever typescript to enforce that the correct options are available for each message type, but these clever tricks result in less obvious usage for consumers of `http-client`. This is part of my [crusage against generics](https://github.com/TBD54566975/tbdex-js/pull/156#issuecomment-1930887063).

Current `sendMessage` method signature:
```typescript
export type SendMessageOptions<T extends Message> = {
  message: T
  replyTo?: T extends Rfq ? string : never
}

static async sendMessage<T extends Message>(opts: SendMessageOptions<T>): Promise<void>
```

Proposed method signatures:
```typescript
static async createExchange(rfq: Rfq, opts?: { replyTo?: string }): Promise<void>

static async submitOrder(order: Order): Promise<void>

static async submitClose(close: Close): Promise<void>
```

The proposed methods are less DRY because DRY APIs are not very tasty.

**Comment by diehuxx** [comment]
@angiejones This would constitute a breaking change in the `http-client` implementation. It would make it harder to use the client incorrectly.

**Comment by angiejones** [comment]
This should be opened against the protocol, yes? Since it would need to be implemented in all SDKs. Would we have time to do this before v1 (end of the month)?

**Comment by diehuxx** [comment]
@angiejones Good call, I opened an issue in the `tbdex` repo to track across implementations https://github.com/TBD54566975/tbdex/issues/254. This issue doesn't affect the TBDex spec, but since it affects multiple of our implementations, makes sense to track it that way.

Regarding timeline, yes this will be done by v1. The javascript and kotlin implementations are ready for review. I will keep an eye on the PRs to close them out as soon as possible.

**Comment by diehuxx** [comment]
@angiejones KT and JS are both merged
