### ISSUE TITLE
Unable to use schemas which are a https url

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/tbdex-js#242]
This is weird, and related to this: 
https://github.com/TBD54566975/tbdex-kt/issues/238

If I try to use https url schema in requiredPaymentDetails I get errors when I try to create an exchange with an RFQ:

```
Failed to verify offering requirements: no schema with key or ref "https://json-schema.org/draft-07/schema#"
```

but http is ok. returned as a 400 from the pfi server (server-http in javascript)

```json
 {
    "errors": [
        {
            "detail": "Failed to verify offering requirements: no schema with key or ref \"https://json-schema.org/draft-07/schema#\""
        }
    ]
}
```

you can reproduce this with an offering with: 

```js
          requiredPaymentDetails: {
            $schema: 'https://json-schema.org/draft-07/schema',
```

**Comment by michaelneale** [comment]
I think there may be a hard coded http somewhere in there for json-schema... as this isn't working even with https

**Comment by decentralgabe** [comment]
this is related to https://github.com/TBD54566975/tbdex/issues/191 
draft 7 you need to use http

**Comment by michaelneale** [comment]
@decentralgabe ok - in this case then this may not be a bug, but does mean android consumers need to allow-list that json-schema.org url for http (as it is quite strict), would that be right?

**Comment by decentralgabe** [comment]
yes I believe that's what we should do

**Comment by michaelneale** [comment]
ok - will close this I think.
