### ISSUE TITLE
Investigate why `TbdexTestVectorsProtocol` tests runs extremely slow sometimes and fix it

### ISSUE THREAD

**Issue by thehenrytsai** [TBD54566975/tbdex-js#252]
`TbdexTestVectorsProtocol` tests that involves JSON parsing SOMETIMES take insane amount of time (~5 seconds per test) to complete causing test timeout failures.

Glancing over the code however I don't see why it'd take milliseconds to complete sometimes and 10x or even 100x some other time. But this causes our CICD pipeline to fail with a misleading error because the test log are hidden when run using `pnpm` (there might be a config to expand it, but that's a separate issue):

<img width="1055" alt="image" src="https://github.com/TBD54566975/tbdex-js/assets/17891086/680fd6a5-b106-48a6-8023-48b9c2488b7f">

**Comment by michaelneale** [comment]
and it is fine when running locally?

**Comment by thehenrytsai** [comment]
@michaelneale, this appears must more rarely locally, but I have seen it when I inherited the repo and was very puzzled by it, but never reproduced it twice in a row.

**Comment by michaelneale** [comment]
I think it is the mocha xml reporter that blows up - I saw it locally a bit too, couldn't work out why. XML isn't a great format for streaming results and can blow up in memory but not sure in this case? 

https://github.com/TBD54566975/tbdex-js/pull/255 I have run that several times with no issue with the default spec reporter

**Comment by michaelneale** [comment]
tried updating to latest mocha stuff - same issue.

**Comment by michaelneale** [comment]
certtainly seems related to xml reporting.

**Comment by thehenrytsai** [comment]
I think #257 should do the job.

**Comment by thehenrytsai** [comment]
#257 addresses this, closing.
